'''
Django settings for cities_backend project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
'''

import environ
from django.utils.translation import ugettext_lazy as _

root = environ.Path(__file__) - 3
env = environ.Env(DEBUG=(bool, False))
env.read_env(env_file=root('.env'))

BASE_DIR = root()

SECRET_KEY = env('SECRET_KEY')
DEBUG = env.bool('DEBUG', default=False)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

AUTH_USER_MODEL = 'auth_ex.User'

DEPENDENCIES = [
    'rest_framework',
    'cities',
]

PROJECT_APPS = [
    'cities_backend',
    'auth_ex.apps.AuthExConfig',
    'cities_ex.apps.CitiesExConfig',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.gis',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
] + DEPENDENCIES + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cities_backend.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ]
    },
}]

WSGI_APPLICATION = 'cities_backend.wsgi.application'

DATABASES = {
    'default': env.db(
        default='postgis://postgres:postgres@postgres:5432/postgres',
    ),
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny', ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
}

USE_TZ = True
TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
LOCALE_PATHS = (root('locale'), )
LANGUAGE_CODE = 'en-us'
LANGUAGES = (
    ('en', _('English')),
)

COUNTRIES = ['GB']
CITIES_CONTINENT_DATA = {
    'EU': ('Europe', 6255148),
}
CITIES_INCLUDE_AIRPORTS_CODES = False
CITIES_INCLUDE_NUMERIC_ALTERNATIVE_NAMES = False
CITIES_DATA_DIR = '/var/data/cities'
CITIES_FILES = {
    'city': {
        'filenames': [f'{country}.zip' for country in COUNTRIES],
    },
    'postal_code': {
        'filenames': [f'{country}.zip' for country in COUNTRIES],
    },
    'alt_name': {
        'filenames': [f'{country}.zip' for country in COUNTRIES],
    }
}
CITIES_LOCALES = ['LANGUAGES']
CITIES_POSTAL_CODES = COUNTRIES

STATIC_URL = '/static/'
STATIC_ROOT = env('STATIC_ROOT', default=(root - 1)('static'))

MEDIA_URL = '/media/'
MEDIA_ROOT = env('MEDIA_ROOT', default=(root - 1)('media'))

if DEBUG:
    INSTALLED_APPS += [
        'debug_toolbar',
        'django_extensions',
        'drf_yasg',
    ]

    MIDDLEWARE = [
        'debug_toolbar.middleware.DebugToolbarMiddleware',
    ] + MIDDLEWARE

    def show_debug_toolbar(request):
        return True

    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': show_debug_toolbar,
    }

    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
